apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapps-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/parama01/myapps.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: myapps

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
